apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - config.yaml
configMapGenerator:
  - name: kafka-metadata
    behavior: merge
    literals:
      # Has to be a config map (not a secret) because of kustomize vars restrictions
      - host=$(KAFKA_HOST)
      - kind=kafka
      - provider=dsyer
      - |
        tags=messaging
        kafka
secretGenerator:
  - name: kafka-secret
    behavior: merge
    literals:
      - port=29092
vars:
  - name: KAFKA_HOST
    objref:
      apiVersion: v1
      kind: Service
      name: kafka-broker
configurations:
  - varreference.yaml