apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - config.yaml
configMapGenerator:
  - name: mysql-metadata
    behavior: merge
    literals:
      - host=$(MYSQL_HOST)
      - kind=mysql
      - provider=dsyer
      - |
        tags=database
        sql
secretGenerator:
  - name: mysql-secret
    behavior: merge
    literals:
      - user=root
      - password=password
      - database=test
vars:
  - name: MYSQL_HOST
    objref:
      apiVersion: v1
      kind: Service
      name: mysql
configurations:
  - varreference.yaml